[
  {
  'name_exp': '4classes',
  'path_from': 'path_to_row_data',
  'path_to': 'path_to_dir',
  'begin_number_file': 1,
  'end_number_file': 100,
  'borders': {0: [0, 7], 1: [7, 9.8], 2: [9.8, 12], 3: [12, 17]},
  'sensor_dist': [1, 1.7, 2.5],
  'subrings': [0.015, 0.0175, 0.02, 0.025],
  'step_angle': 0.7853981633974483,
  'data_mode': 'one_time'
  }
]